/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security.cert;

public abstract class Certificate extends java.lang.Object implements java.io.Serializable
{


   /*@ requires true; ensures true; assignable \everything; */
   protected Certificate(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public final java.lang.String getType();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; signals (java.security.cert.CertificateEncodingException e) true; */
   public abstract byte[] getEncoded() throws java.security.cert.CertificateEncodingException;

   /*@ requires true; ensures true; assignable \everything; signals (java.security.cert.CertificateException e) true; signals (java.security.NoSuchAlgorithmException e) true; signals (java.security.InvalidKeyException e) true; signals (java.security.NoSuchProviderException e) true; signals (java.security.SignatureException e) true; */
   public abstract void verify(java.security.PublicKey arg0) throws java.security.cert.CertificateException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException, java.security.NoSuchProviderException, java.security.SignatureException;

   /*@ requires true; ensures true; assignable \everything; signals (java.security.cert.CertificateException e) true; signals (java.security.NoSuchAlgorithmException e) true; signals (java.security.InvalidKeyException e) true; signals (java.security.NoSuchProviderException e) true; signals (java.security.SignatureException e) true; */
   public abstract void verify(java.security.PublicKey arg0, java.lang.String arg1) throws java.security.cert.CertificateException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException, java.security.NoSuchProviderException, java.security.SignatureException;

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.lang.String toString();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.security.PublicKey getPublicKey();

   /*@ requires true; ensures true; assignable \everything; signals (java.io.ObjectStreamException e) true; */
   protected java.lang.Object writeReplace() throws java.io.ObjectStreamException;
}
