/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security.cert;

public class CertificateEncodingException extends java.security.cert.CertificateException
{


   /*@ requires true; ensures true; assignable \everything; */
   public CertificateEncodingException();

   /*@ requires true; ensures true; assignable \everything; */
   public CertificateEncodingException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public CertificateEncodingException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public CertificateEncodingException(java.lang.Throwable arg0);
}
