/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package sun.reflect;

public interface ConstructorAccessor
{


   /*@ requires true; ensures true; assignable \everything; signals (java.lang.InstantiationException e) true; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.reflect.InvocationTargetException e) true; */
   public java.lang.Object newInstance(java.lang.Object[] arg0) throws java.lang.InstantiationException, java.lang.IllegalArgumentException, java.lang.reflect.InvocationTargetException;
}
