/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package sun.reflect;

public interface FieldAccessor
{


   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public java.lang.Object get(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public boolean getBoolean(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public byte getByte(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public char getChar(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public short getShort(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public int getInt(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public long getLong(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public float getFloat(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; */
   public double getDouble(java.lang.Object arg0) throws java.lang.IllegalArgumentException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void set(java.lang.Object arg0, java.lang.Object arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setBoolean(java.lang.Object arg0, boolean arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setByte(java.lang.Object arg0, byte arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setChar(java.lang.Object arg0, char arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setShort(java.lang.Object arg0, short arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setInt(java.lang.Object arg0, int arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setLong(java.lang.Object arg0, long arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setFloat(java.lang.Object arg0, float arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.IllegalArgumentException e) true; signals (java.lang.IllegalAccessException e) true; */
   public void setDouble(java.lang.Object arg0, double arg1) throws java.lang.IllegalArgumentException, java.lang.IllegalAccessException;
}
