/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public abstract class ContentHandler extends java.lang.Object
{


   /*@ requires true; ensures true; assignable \everything; */
   public ContentHandler();

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public abstract java.lang.Object getContent(java.net.URLConnection arg0) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.lang.Object getContent(java.net.URLConnection arg0, java.lang.Class[] arg1) throws java.io.IOException;
}
