/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public interface ContentHandlerFactory
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.net.ContentHandler createContentHandler(java.lang.String arg0);
}
