/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

class InetAddress$InetAddressHolder extends java.lang.Object
{
   java.lang.String hostName;
   int address;
   int family;

}
