/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

interface InetAddressImpl
{


   /*@ requires true; ensures true; assignable \everything; signals (java.net.UnknownHostException e) true; */
   public java.lang.String getLocalHostName() throws java.net.UnknownHostException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.UnknownHostException e) true; */
   public java.net.InetAddress[] lookupAllHostAddr(java.lang.String arg0) throws java.net.UnknownHostException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.UnknownHostException e) true; */
   public java.lang.String getHostByAddr(byte[] arg0) throws java.net.UnknownHostException;

   /*@ requires true; ensures true; assignable \everything; */
   public java.net.InetAddress anyLocalAddress();

   /*@ requires true; ensures true; assignable \everything; */
   public java.net.InetAddress loopbackAddress();

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public boolean isReachable(java.net.InetAddress arg0, int arg1, java.net.NetworkInterface arg2, int arg3) throws java.io.IOException;
}
