/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public class MalformedURLException extends java.io.IOException
{


   /*@ requires true; ensures true; assignable \everything; */
   public MalformedURLException();

   /*@ requires true; ensures true; assignable \everything; */
   public MalformedURLException(java.lang.String arg0);
}
