/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public final class NetworkInterface extends java.lang.Object
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getName();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Enumeration getInetAddresses();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.List getInterfaceAddresses();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Enumeration getSubInterfaces();

   /*@ requires true; ensures true; assignable \everything; */
   public java.net.NetworkInterface getParent();

   /*@ requires true; ensures true; assignable \everything; */
   public int getIndex();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getDisplayName();

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public static java.net.NetworkInterface getByName(java.lang.String arg0) throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public static java.net.NetworkInterface getByIndex(int arg0) throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public static java.net.NetworkInterface getByInetAddress(java.net.InetAddress arg0) throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public static java.util.Enumeration getNetworkInterfaces() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public boolean isUp() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public boolean isLoopback() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public boolean isPointToPoint() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public boolean supportsMulticast() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public byte[] getHardwareAddress() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; signals (java.net.SocketException e) true; */
   public int getMTU() throws java.net.SocketException;

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isVirtual();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
