/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public final class Proxy$Type extends java.lang.Enum
{
   public final static java.net.Proxy$Type DIRECT;
   public final static java.net.Proxy$Type HTTP;
   public final static java.net.Proxy$Type SOCKS;


   /*@ requires true; ensures true; assignable \everything; */
   public static java.net.Proxy$Type[] values();

   /*@ requires true; ensures true; assignable \everything; */
   public static java.net.Proxy$Type valueOf(java.lang.String arg0);
}
