/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public class Proxy extends java.lang.Object
{
   public final static java.net.Proxy NO_PROXY;


   /*@ requires true; ensures true; assignable \everything; */
   public Proxy(java.net.Proxy$Type arg0, java.net.SocketAddress arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.net.Proxy$Type type();

   /*@ requires true; ensures true; assignable \everything; */
   public java.net.SocketAddress address();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();

   /*@ requires true; ensures true; assignable \everything; */
   public final boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public final int hashCode();
}
