/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public class UnknownHostException extends java.io.IOException
{


   /*@ requires true; ensures true; assignable \everything; */
   public UnknownHostException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public UnknownHostException();
}
