/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public class URISyntaxException extends java.lang.Exception
{


   /*@ requires true; ensures true; assignable \everything; */
   public URISyntaxException(java.lang.String arg0, java.lang.String arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public URISyntaxException(java.lang.String arg0, java.lang.String arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getInput();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getReason();

   /*@ requires true; ensures true; assignable \everything; */
   public int getIndex();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getMessage();
}
