/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.net;

public abstract class URLStreamHandler extends java.lang.Object
{


   /*@ requires true; ensures true; assignable \everything; */
   public URLStreamHandler();

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   protected abstract java.net.URLConnection openConnection(java.net.URL arg0) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   protected java.net.URLConnection openConnection(java.net.URL arg0, java.net.Proxy arg1) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; */
   protected void parseURL(java.net.URL arg0, java.lang.String arg1, int arg2, int arg3);

   /*@ requires true; ensures true; assignable \everything; */
   protected int getDefaultPort();

   /*@ requires true; ensures true; assignable \everything; */
   protected boolean equals(java.net.URL arg0, java.net.URL arg1);

   /*@ requires true; ensures true; assignable \everything; */
   protected int hashCode(java.net.URL arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected boolean sameFile(java.net.URL arg0, java.net.URL arg1);

   /*@ requires true; ensures true; assignable \everything; */
   protected java.net.InetAddress getHostAddress(java.net.URL arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected boolean hostsEqual(java.net.URL arg0, java.net.URL arg1);

   /*@ requires true; ensures true; assignable \everything; */
   protected java.lang.String toExternalForm(java.net.URL arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected void setURL(java.net.URL arg0, java.lang.String arg1, java.lang.String arg2, int arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7, java.lang.String arg8);

   /*@ requires true; ensures true; assignable \everything; */
   protected void setURL(java.net.URL arg0, java.lang.String arg1, java.lang.String arg2, int arg3, java.lang.String arg4, java.lang.String arg5);
}
