/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file.attribute;

public interface FileAttributeView extends java.nio.file.attribute.AttributeView
{

}
