/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file.attribute;

public interface FileAttribute
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String name();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object value();
}
