/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file.attribute;

public abstract class UserPrincipalLookupService extends java.lang.Object
{


   /*@ requires true; ensures true; assignable \everything; */
   protected UserPrincipalLookupService();

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public abstract java.nio.file.attribute.UserPrincipal lookupPrincipalByName(java.lang.String arg0) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public abstract java.nio.file.attribute.GroupPrincipal lookupPrincipalByGroupName(java.lang.String arg0) throws java.io.IOException;
}
