/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.charset;

public class CodingErrorAction extends java.lang.Object
{
   public final static java.nio.charset.CodingErrorAction IGNORE;
   public final static java.nio.charset.CodingErrorAction REPLACE;
   public final static java.nio.charset.CodingErrorAction REPORT;


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
