/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang.ref;

public abstract class Reference extends java.lang.Object
{
   java.lang.ref.ReferenceQueue queue;
   java.lang.ref.Reference next;


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object get();

   /*@ requires true; ensures true; assignable \everything; */
   public void clear();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isEnqueued();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean enqueue();
}
