/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang.ref;

public class WeakReference extends java.lang.ref.Reference
{


   /*@ requires true; ensures true; assignable \everything; */
   public WeakReference(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public WeakReference(java.lang.Object arg0, java.lang.ref.ReferenceQueue arg1);
}
