/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.channels;

public class FileChannel$MapMode extends java.lang.Object
{
   public final static java.nio.channels.FileChannel$MapMode READ_ONLY;
   public final static java.nio.channels.FileChannel$MapMode READ_WRITE;
   public final static java.nio.channels.FileChannel$MapMode PRIVATE;


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
