/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public class CodeSource extends java.lang.Object implements java.io.Serializable
{


   /*@ requires true; ensures true; assignable \everything; */
   public CodeSource(java.net.URL arg0, java.security.cert.Certificate[] arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public CodeSource(java.net.URL arg0, java.security.CodeSigner[] arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public final java.net.URL getLocation();

   /*@ requires true; ensures true; assignable \everything; */
   public final java.security.cert.Certificate[] getCertificates();

   /*@ requires true; ensures true; assignable \everything; */
   public final java.security.CodeSigner[] getCodeSigners();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean implies(java.security.CodeSource arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
