/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public class GeneralSecurityException extends java.lang.Exception
{


   /*@ requires true; ensures true; assignable \everything; */
   public GeneralSecurityException();

   /*@ requires true; ensures true; assignable \everything; */
   public GeneralSecurityException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public GeneralSecurityException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public GeneralSecurityException(java.lang.Throwable arg0);
}
