/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public interface Guard
{


   /*@ requires true; ensures true; assignable \everything; signals (java.lang.SecurityException e) true; */
   public void checkGuard(java.lang.Object arg0) throws java.lang.SecurityException;
}
