/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public interface Key extends java.io.Serializable
{
   public final static long serialVersionUID = 6603384152749567654L;


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getAlgorithm();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getFormat();

   /*@ requires true; ensures true; assignable \everything; */
   public byte[] getEncoded();
}
