/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public class NoSuchAlgorithmException extends java.security.GeneralSecurityException
{


   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchAlgorithmException();

   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchAlgorithmException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchAlgorithmException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchAlgorithmException(java.lang.Throwable arg0);
}
