/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public class NoSuchProviderException extends java.security.GeneralSecurityException
{


   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchProviderException();

   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchProviderException(java.lang.String arg0);
}
