/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public abstract class PermissionCollection extends java.lang.Object implements java.io.Serializable
{


   /*@ requires true; ensures true; assignable \everything; */
   public PermissionCollection();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract void add(java.security.Permission arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract boolean implies(java.security.Permission arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.util.Enumeration elements();

   /*@ requires true; ensures true; assignable \everything; */
   public void setReadOnly();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isReadOnly();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
