/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

final class ProtectionDomain$Key extends java.lang.Object
{
   final java.security.ProtectionDomain this$0;

}
