/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public interface PublicKey extends java.security.Key
{
   public final static long serialVersionUID = 7187392471159151072L;

}
