/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.security;

public final class Timestamp extends java.lang.Object implements java.io.Serializable
{


   /*@ requires true; ensures true; assignable \everything; */
   public Timestamp(java.util.Date arg0, java.security.cert.CertPath arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Date getTimestamp();

   /*@ requires true; ensures true; assignable \everything; */
   public java.security.cert.CertPath getSignerCertPath();

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
