/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util.concurrent;

public interface Executor
{


   /*@ requires true; ensures true; assignable \everything; */
   public void execute(java.lang.Runnable arg0);
}
