/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util.concurrent;

public class ExecutionException extends java.lang.Exception
{


   /*@ requires true; ensures true; assignable \everything; */
   protected ExecutionException();

   /*@ requires true; ensures true; assignable \everything; */
   protected ExecutionException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public ExecutionException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public ExecutionException(java.lang.Throwable arg0);
}
