/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util.concurrent;

public class TimeoutException extends java.lang.Exception
{


   /*@ requires true; ensures true; assignable \everything; */
   public TimeoutException();

   /*@ requires true; ensures true; assignable \everything; */
   public TimeoutException(java.lang.String arg0);
}
