/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio;

public final class ByteOrder extends java.lang.Object
{
   public final static java.nio.ByteOrder BIG_ENDIAN;
   public final static java.nio.ByteOrder LITTLE_ENDIAN;


   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.ByteOrder nativeOrder();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
