/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio;

public abstract class IntBuffer extends java.nio.Buffer implements java.lang.Comparable
{
   final int[] hb;
   final int offset;
   boolean isReadOnly;


   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.IntBuffer allocate(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.IntBuffer wrap(int[] arg0, int arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.IntBuffer wrap(int[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.IntBuffer slice();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.IntBuffer duplicate();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.IntBuffer asReadOnlyBuffer();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract int get();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.IntBuffer put(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract int get(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.IntBuffer put(int arg0, int arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.nio.IntBuffer get(int[] arg0, int arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public java.nio.IntBuffer get(int[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.nio.IntBuffer put(java.nio.IntBuffer arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.nio.IntBuffer put(int[] arg0, int arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public final java.nio.IntBuffer put(int[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public final boolean hasArray();

   /*@ requires true; ensures true; assignable \everything; */
   public final int[] array();

   /*@ requires true; ensures true; assignable \everything; */
   public final int arrayOffset();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.IntBuffer compact();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract boolean isDirect();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int compareTo(java.nio.IntBuffer arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.nio.ByteOrder order();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object array();

   /*@ requires true; ensures true; assignable \everything; */
   public int compareTo(java.lang.Object arg0);
}
