/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio;

public abstract class MappedByteBuffer extends java.nio.ByteBuffer
{


   /*@ requires true; ensures true; assignable \everything; */
   public final boolean isLoaded();

   /*@ requires true; ensures true; assignable \everything; */
   public final java.nio.MappedByteBuffer load();

   /*@ requires true; ensures true; assignable \everything; */
   public final java.nio.MappedByteBuffer force();
}
