/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.io;

public final class FileDescriptor extends java.lang.Object
{
   public final static java.io.FileDescriptor in;
   public final static java.io.FileDescriptor out;
   public final static java.io.FileDescriptor err;


   /*@ requires true; ensures true; assignable \everything; */
   public FileDescriptor();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean valid();

   /*@ requires true; ensures true; assignable \everything; signals (java.io.SyncFailedException e) true; */
   public void sync() throws java.io.SyncFailedException;
}
