/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.io;

public class FileNotFoundException extends java.io.IOException
{


   /*@ requires true; ensures true; assignable \everything; */
   public FileNotFoundException();

   /*@ requires true; ensures true; assignable \everything; */
   public FileNotFoundException(java.lang.String arg0);
}
