/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.io;

public class IOException extends java.lang.Exception
{
   final static long serialVersionUID = 7818375828146090155L;


   /*@ requires true; ensures true; assignable \everything; */
   public IOException();

   /*@ requires true; ensures true; assignable \everything; */
   public IOException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public IOException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public IOException(java.lang.Throwable arg0);
}
