/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.io;

public abstract class ObjectStreamException extends java.io.IOException
{


   /*@ requires true; ensures true; assignable \everything; */
   protected ObjectStreamException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected ObjectStreamException();
}
