/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.io;

public class PrintWriter extends java.io.Writer
{
   protected java.io.Writer out;


   /*@ requires true; ensures true; assignable \everything; */
   public PrintWriter(java.io.Writer arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public PrintWriter(java.io.Writer arg0, boolean arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public PrintWriter(java.io.OutputStream arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public PrintWriter(java.io.OutputStream arg0, boolean arg1);

   /*@ requires true; ensures true; assignable \everything; signals (java.io.FileNotFoundException e) true; */
   public PrintWriter(java.lang.String arg0) throws java.io.FileNotFoundException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.FileNotFoundException e) true; signals (java.io.UnsupportedEncodingException e) true; */
   public PrintWriter(java.lang.String arg0, java.lang.String arg1) throws java.io.FileNotFoundException, java.io.UnsupportedEncodingException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.FileNotFoundException e) true; */
   public PrintWriter(java.io.File arg0) throws java.io.FileNotFoundException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.FileNotFoundException e) true; signals (java.io.UnsupportedEncodingException e) true; */
   public PrintWriter(java.io.File arg0, java.lang.String arg1) throws java.io.FileNotFoundException, java.io.UnsupportedEncodingException;

   /*@ requires true; ensures true; assignable \everything; */
   public void flush();

   /*@ requires true; ensures true; assignable \everything; */
   public void close();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean checkError();

   /*@ requires true; ensures true; assignable \everything; */
   protected void setError();

   /*@ requires true; ensures true; assignable \everything; */
   protected void clearError();

   /*@ requires true; ensures true; assignable \everything; */
   public void write(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void write(char[] arg0, int arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public void write(char[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void write(java.lang.String arg0, int arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public void write(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(boolean arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(char arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(long arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(float arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(double arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(char[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void print(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println();

   /*@ requires true; ensures true; assignable \everything; */
   public void println(boolean arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(char arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(long arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(float arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(double arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(char[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void println(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter printf(java.lang.String arg0, java.lang.Object[] arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter printf(java.util.Locale arg0, java.lang.String arg1, java.lang.Object[] arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter format(java.lang.String arg0, java.lang.Object[] arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter format(java.util.Locale arg0, java.lang.String arg1, java.lang.Object[] arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter append(java.lang.CharSequence arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter append(java.lang.CharSequence arg0, int arg1, int arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public java.io.PrintWriter append(char arg0);

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.io.Writer append(char arg0) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.io.Writer append(java.lang.CharSequence arg0, int arg1, int arg2) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.io.Writer append(java.lang.CharSequence arg0) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.lang.Appendable append(char arg0) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.lang.Appendable append(java.lang.CharSequence arg0, int arg1, int arg2) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.lang.Appendable append(java.lang.CharSequence arg0) throws java.io.IOException;
}
