/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.io;

public class SyncFailedException extends java.io.IOException
{


   /*@ requires true; ensures true; assignable \everything; */
   public SyncFailedException(java.lang.String arg0);
}
