/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public final class AccessMode extends java.lang.Enum
{
   public final static java.nio.file.AccessMode READ;
   public final static java.nio.file.AccessMode WRITE;
   public final static java.nio.file.AccessMode EXECUTE;


   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.file.AccessMode[] values();

   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.file.AccessMode valueOf(java.lang.String arg0);
}
