/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public interface DirectoryStream extends java.io.Closeable, java.lang.Iterable
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Iterator iterator();
}
