/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public interface DirectoryStream$Filter
{


   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public boolean accept(java.lang.Object arg0) throws java.io.IOException;
}
