/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public final class LinkOption extends java.lang.Enum implements java.nio.file.OpenOption, java.nio.file.CopyOption
{
   public final static java.nio.file.LinkOption NOFOLLOW_LINKS;


   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.file.LinkOption[] values();

   /*@ requires true; ensures true; assignable \everything; */
   public static java.nio.file.LinkOption valueOf(java.lang.String arg0);
}
