/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public interface PathMatcher
{


   /*@ requires true; ensures true; assignable \everything; */
   public boolean matches(java.nio.file.Path arg0);
}
