/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public interface Watchable
{


   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.nio.file.WatchKey register(java.nio.file.WatchService arg0, java.nio.file.WatchEvent$Kind[] arg1, java.nio.file.WatchEvent$Modifier[] arg2) throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public java.nio.file.WatchKey register(java.nio.file.WatchService arg0, java.nio.file.WatchEvent$Kind[] arg1) throws java.io.IOException;
}
