/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public interface WatchKey
{


   /*@ requires true; ensures true; assignable \everything; */
   public boolean isValid();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.List pollEvents();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean reset();

   /*@ requires true; ensures true; assignable \everything; */
   public void cancel();

   /*@ requires true; ensures true; assignable \everything; */
   public java.nio.file.Watchable watchable();
}
