/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.nio.file;

public interface WatchService extends java.io.Closeable
{


   /*@ requires true; ensures true; assignable \everything; signals (java.io.IOException e) true; */
   public void close() throws java.io.IOException;

   /*@ requires true; ensures true; assignable \everything; */
   public java.nio.file.WatchKey poll();

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.InterruptedException e) true; */
   public java.nio.file.WatchKey poll(long arg0, java.util.concurrent.TimeUnit arg1) throws java.lang.InterruptedException;

   /*@ requires true; ensures true; assignable \everything; signals (java.lang.InterruptedException e) true; */
   public java.nio.file.WatchKey take() throws java.lang.InterruptedException;
}
