/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public interface Comparator
{
    /*@ invariant true; @*/
    /*@ accessible \inv: \nothing; @*/


   /*@ public normal_behavior
     @ requires
     @   true;
     @ ensures
     @   \result == compare(arg0, arg1);
     @ accessible arg0.*, arg1.*;
     @ assignable
     @   \strictly_nothing;
     @*/
   public int /*@ helper @*/ compare(/*@ nullable @*/ java.lang.Object arg0, /*@ nullable @*/ java.lang.Object arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);
}
