/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public abstract class Dictionary extends java.lang.Object
{


   /*@ requires true; ensures true; assignable \everything; */
   public Dictionary();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract int size();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract boolean isEmpty();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.util.Enumeration keys();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.util.Enumeration elements();

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.lang.Object get(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.lang.Object put(java.lang.Object arg0, java.lang.Object arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public abstract java.lang.Object remove(java.lang.Object arg0);
}
