/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public interface Enumeration
{


   /*@ requires true; ensures true; assignable \everything; */
   public boolean hasMoreElements();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object nextElement();
}
