/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public class InvalidPropertiesFormatException extends java.io.IOException
{


   /*@ requires true; ensures true; assignable \everything; */
   public InvalidPropertiesFormatException(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public InvalidPropertiesFormatException(java.lang.String arg0);
}
