/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public interface List extends java.util.Collection
{


   /*@ requires true; ensures true; assignable \everything; */
   public int size();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isEmpty();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean contains(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Iterator iterator();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object[] toArray();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object[] toArray(java.lang.Object[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean add(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean remove(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean containsAll(java.util.Collection arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean addAll(java.util.Collection arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean addAll(int arg0, java.util.Collection arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean removeAll(java.util.Collection arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean retainAll(java.util.Collection arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void clear();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object get(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object set(int arg0, java.lang.Object arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public void add(int arg0, java.lang.Object arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object remove(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int indexOf(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int lastIndexOf(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.ListIterator listIterator();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.ListIterator listIterator(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.List subList(int arg0, int arg1);
}
