/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public final class Locale$Category extends java.lang.Enum
{
   public final static java.util.Locale$Category DISPLAY;
   public final static java.util.Locale$Category FORMAT;
   final java.lang.String languageKey;
   final java.lang.String scriptKey;
   final java.lang.String countryKey;
   final java.lang.String variantKey;


   /*@ requires true; ensures true; assignable \everything; */
   public static java.util.Locale$Category[] values();

   /*@ requires true; ensures true; assignable \everything; */
   public static java.util.Locale$Category valueOf(java.lang.String arg0);
}
