/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public interface Map$Entry
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object getKey();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object getValue();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object setValue(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();
}
