/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public class MissingResourceException extends java.lang.RuntimeException
{


   /*@ requires true; ensures true; assignable \everything; */
   public MissingResourceException(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getClassName();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getKey();
}
