/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public interface SortedMap extends java.util.Map
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Comparator comparator();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.SortedMap subMap(java.lang.Object arg0, java.lang.Object arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.SortedMap headMap(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.SortedMap tailMap(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object firstKey();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object lastKey();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Set keySet();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Collection values();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Set entrySet();
}
