/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

public class WeakHashMap extends java.util.AbstractMap implements java.util.Map
{
   java.util.WeakHashMap$Entry[] table;
   int modCount;
   final static int ALTERNATIVE_HASHING_THRESHOLD_DEFAULT = 2147483647;
   boolean useAltHashing;
   final int hashSeed;


   /*@ requires true; ensures true; assignable \everything; */
   public WeakHashMap(int arg0, float arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public WeakHashMap(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public WeakHashMap();

   /*@ requires true; ensures true; assignable \everything; */
   public WeakHashMap(java.util.Map arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int size();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isEmpty();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object get(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean containsKey(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object put(java.lang.Object arg0, java.lang.Object arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public void putAll(java.util.Map arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object remove(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void clear();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean containsValue(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Set keySet();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Collection values();

   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Set entrySet();
}
