/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.util;

class WeakHashMap$Entry extends java.lang.ref.WeakReference implements java.util.Map$Entry
{
   java.lang.Object value;
   int hash;
   java.util.WeakHashMap$Entry next;


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object getKey();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object getValue();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Object setValue(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
