/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class ArrayIndexOutOfBoundsException extends java.lang.IndexOutOfBoundsException
{


   /*@ requires true; ensures true; assignable \everything; */
   public ArrayIndexOutOfBoundsException();

   /*@ requires true; ensures true; assignable \everything; */
   public ArrayIndexOutOfBoundsException(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public ArrayIndexOutOfBoundsException(java.lang.String arg0);
}
