/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class AssertionError extends java.lang.Error
{


   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError();

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(boolean arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(char arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(long arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(float arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(double arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public AssertionError(java.lang.String arg0, java.lang.Throwable arg1);
}
