/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public interface AutoCloseable
{


   /*@ requires true; ensures true; assignable \everything; signals (java.lang.Exception e) true; */
   public void close() throws java.lang.Exception;
}
