/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public interface CharSequence
{


   /*@ requires true; ensures true; assignable \everything; */
   public int length();

   /*@ requires true; ensures true; assignable \everything; */
   public char charAt(int arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.CharSequence subSequence(int arg0, int arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();
}
