/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class ClassNotFoundException extends java.lang.ReflectiveOperationException
{


   /*@ requires true; ensures true; assignable \everything; */
   public ClassNotFoundException();

   /*@ requires true; ensures true; assignable \everything; */
   public ClassNotFoundException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public ClassNotFoundException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable getException();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable getCause();
}
