/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class CloneNotSupportedException extends java.lang.Exception
{


   /*@ requires true; ensures true; assignable \everything; */
   public CloneNotSupportedException();

   /*@ requires true; ensures true; assignable \everything; */
   public CloneNotSupportedException(java.lang.String arg0);
}
