/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class Error extends java.lang.Throwable
{
   final static long serialVersionUID = 4980196508277280342L;


   /*@ requires true; ensures true; assignable \everything; */
   public Error();

   /*@ requires true; ensures true; assignable \everything; */
   public Error(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public Error(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public Error(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected Error(java.lang.String arg0, java.lang.Throwable arg1, boolean arg2, boolean arg3);
}
