/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class Exception extends java.lang.Throwable
{
   final static long serialVersionUID = -3387516993124229948L;


   /*@ requires true; ensures true; assignable \everything; */
   public Exception();

   /*@ requires true; ensures true; assignable \everything; */
   public Exception(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public Exception(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public Exception(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected Exception(java.lang.String arg0, java.lang.Throwable arg1, boolean arg2, boolean arg3);
}
