/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class ExceptionInInitializerError extends java.lang.LinkageError
{


   /*@ requires true; ensures true; assignable \everything; */
   public ExceptionInInitializerError();

   /*@ requires true; ensures true; assignable \everything; */
   public ExceptionInInitializerError(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public ExceptionInInitializerError(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable getException();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable getCause();
}
