/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class IllegalAccessException extends java.lang.ReflectiveOperationException
{


   /*@ requires true; ensures true; assignable \everything; */
   public IllegalAccessException();

   /*@ requires true; ensures true; assignable \everything; */
   public IllegalAccessException(java.lang.String arg0);
}
