/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class InterruptedException extends java.lang.Exception
{


   /*@ requires true; ensures true; assignable \everything; */
   public InterruptedException();

   /*@ requires true; ensures true; assignable \everything; */
   public InterruptedException(java.lang.String arg0);
}
