/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public interface Iterable
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.util.Iterator iterator();
}
