/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class NegativeArraySizeException extends java.lang.RuntimeException
{


   /*@ requires true; ensures true; assignable \everything; */
   public NegativeArraySizeException();

   /*@ requires true; ensures true; assignable \everything; */
   public NegativeArraySizeException(java.lang.String arg0);
}
