/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class NoSuchFieldException extends java.lang.ReflectiveOperationException
{


   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchFieldException();

   /*@ requires true; ensures true; assignable \everything; */
   public NoSuchFieldException(java.lang.String arg0);
}
