/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class NumberFormatException extends java.lang.IllegalArgumentException
{
   final static long serialVersionUID = -2848938806368998894L;


   /*@ requires true; ensures true; assignable \everything; */
   public NumberFormatException();

   /*@ requires true; ensures true; assignable \everything; */
   public NumberFormatException(java.lang.String arg0);
}
