/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class OutOfMemoryError extends java.lang.VirtualMachineError
{


   /*@ requires true; ensures true; assignable \everything; */
   public OutOfMemoryError();

   /*@ requires true; ensures true; assignable \everything; */
   public OutOfMemoryError(java.lang.String arg0);
}
