/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class ReflectiveOperationException extends java.lang.Exception
{
   final static long serialVersionUID = 123456789L;


   /*@ requires true; ensures true; assignable \everything; */
   public ReflectiveOperationException();

   /*@ requires true; ensures true; assignable \everything; */
   public ReflectiveOperationException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public ReflectiveOperationException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public ReflectiveOperationException(java.lang.Throwable arg0);
}
