/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class RuntimeException extends java.lang.Exception
{
   final static long serialVersionUID = -7034897190745766939L;


   /*@ requires true; ensures true; assignable \everything; */
   public RuntimeException();

   /*@ requires true; ensures true; assignable \everything; */
   public RuntimeException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public RuntimeException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public RuntimeException(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected RuntimeException(java.lang.String arg0, java.lang.Throwable arg1, boolean arg2, boolean arg3);
}
