/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class SecurityException extends java.lang.RuntimeException
{


   /*@ requires true; ensures true; assignable \everything; */
   public SecurityException();

   /*@ requires true; ensures true; assignable \everything; */
   public SecurityException(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public SecurityException(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public SecurityException(java.lang.Throwable arg0);
}
