/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public final class StackTraceElement extends java.lang.Object implements java.io.Serializable
{


   /*@ requires true; ensures true; assignable \everything; */
   public StackTraceElement(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getFileName();

   /*@ requires true; ensures true; assignable \everything; */
   public int getLineNumber();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getClassName();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getMethodName();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isNativeMethod();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean equals(java.lang.Object arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public int hashCode();
}
