/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public class Throwable extends java.lang.Object implements java.io.Serializable
{
   final static boolean $assertionsDisabled;


   /*@ requires true; ensures true; assignable \everything; */
   public Throwable();

   /*@ requires true; ensures true; assignable \everything; */
   public Throwable(java.lang.String arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public Throwable(java.lang.String arg0, java.lang.Throwable arg1);

   /*@ requires true; ensures true; assignable \everything; */
   public Throwable(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   protected Throwable(java.lang.String arg0, java.lang.Throwable arg1, boolean arg2, boolean arg3);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getMessage();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getLocalizedMessage();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable getCause();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable initCause(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String toString();

   /*@ requires true; ensures true; assignable \everything; */
   public void printStackTrace();

   /*@ requires true; ensures true; assignable \everything; */
   public void printStackTrace(java.io.PrintStream arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public void printStackTrace(java.io.PrintWriter arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Throwable fillInStackTrace();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.StackTraceElement[] getStackTrace();

   /*@ requires true; ensures true; assignable \everything; */
   public void setStackTrace(java.lang.StackTraceElement[] arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public final void addSuppressed(java.lang.Throwable arg0);

   /*@ requires true; ensures true; assignable \everything; */
   public final java.lang.Throwable[] getSuppressed();
}
