/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang;

public abstract class VirtualMachineError extends java.lang.Error
{


   /*@ requires true; ensures true; assignable \everything; */
   public VirtualMachineError();

   /*@ requires true; ensures true; assignable \everything; */
   public VirtualMachineError(java.lang.String arg0);
}
