/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang.reflect;

public interface Member
{
   public final static int PUBLIC = 0;
   public final static int DECLARED = 1;


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.Class getDeclaringClass();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getName();

   /*@ requires true; ensures true; assignable \everything; */
   public int getModifiers();

   /*@ requires true; ensures true; assignable \everything; */
   public boolean isSynthetic();
}
