/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed Nov 26 11:26:00 CET 2014
 */
package java.lang.reflect;

public interface TypeVariable extends java.lang.reflect.Type
{


   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.reflect.Type[] getBounds();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.reflect.GenericDeclaration getGenericDeclaration();

   /*@ requires true; ensures true; assignable \everything; */
   public java.lang.String getName();
}
